package com.example.tournament_data.model;

import java.time.LocalDateTime;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "matches")
@Schema(description = "Match entity representing a cricket match between two teams")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Match {
    @Id
    @Schema(description = "Unique identifier of the match (auto-generated by MongoDB)", example = "64a1b2c3d4e5f6g7h8i9j0k1", accessMode = Schema.AccessMode.READ_ONLY)
    private String id;

    @NotBlank(message = "Venue is required")
    @Size(min = 2, max = 150, message = "Venue must be between 2 and 150 characters")
    @Schema(description = "Stadium/Ground where the match is being played", example = "Wankhede Stadium, Mumbai", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 150)
    private String venue;

    @NotNull(message = "Match date and time is required")
    @Schema(description = "Date and time of the match (ISO 8601 format)", example = "2024-04-15T19:30:00", requiredMode = Schema.RequiredMode.REQUIRED, type = "string", format = "date-time")
    private LocalDateTime date;

    @NotBlank(message = "First team ID is required")
    @Schema(description = "Team ID of the first team (home team)", example = "64a1b2c3d4e5f6g7h8i9j0k2", requiredMode = Schema.RequiredMode.REQUIRED)
    private String firstTeam; // id of team

    @NotBlank(message = "Second team ID is required")
    @Schema(description = "Team ID of the second team (away team)", example = "64a1b2c3d4e5f6g7h8i9j0k3", requiredMode = Schema.RequiredMode.REQUIRED)
    private String secondTeam; // id of team

    @NotBlank(message = "Match status is required")
    @Pattern(regexp = "^(SCHEDULED|COMPLETED)$", message = "Status must be: SCHEDULED, LIVE, COMPLETED, CANCELLED, or ABANDONED")
    @Schema(description = "Current status of the match", example = "SCHEDULED", requiredMode = Schema.RequiredMode.REQUIRED, allowableValues = {
            "SCHEDULED", "LIVE", "COMPLETED", "CANCELLED", "ABANDONED" })
    private String status; // COMPLETE or SCHEDULED

    @Valid
    @Schema(description = "Match result details (only applicable when status is COMPLETED)", nullable = true)
    private Result result;
}
