package com.example.tournament_data.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "players")
@Schema(description = "Player entity representing a cricket player in the tournament")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Player {
    @Transient
    public static final String SEQUENCE_NAME = "players_sequence";

    @Id
    @Schema(description = "Unique identifier of the player (auto-generated by MongoDB)", example = "64a1b2c3d4e5f6g7h8i9j0k1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer id; // automatically created by MongoDB

    @Schema(description = "Team ID the player belongs to (null if not assigned to any team)", example = "64a1b2c3d4e5f6g7h8i9j0k2", nullable = true)
    private Integer teamId; // will refer to the team Object ID, can also be null if player is not in any
                           // team

    @NotBlank(message = "Player Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Schema(description = "Full name of the player", example = "Virat Kohli", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String name;

    @NotBlank(message = "Role is required")
    @Pattern(regexp = "^(Batsman|Bowler|All-Rounder|Wicket-Keeper)$", message = "Role must be: Batsman, Bowler, All-Rounder, or Wicket-Keeper")
    @Schema(description = "Playing role of the player in the team", example = "Batsman", requiredMode = Schema.RequiredMode.REQUIRED, allowableValues = {
            "Batsman", "Bowler", "All-Rounder", "Wicket-Keeper" })
    private String role;

    @NotBlank(message = "Batting style is required")
    @Pattern(regexp = "^(Right-Handed|Left-Handed)$", message = "Batting style must be: Right-Handed or Left-Handed")
    @Schema(description = "Batting hand preference of the player", example = "Right-Handed", requiredMode = Schema.RequiredMode.REQUIRED, allowableValues = {
            "Right-Handed", "Left-Handed" })
    private String battingStyle;

    // Can be null for pure batsmen, so not using @NotBlank
    @Pattern(regexp = "^(Right-Arm Fast|Left-Arm Fast|Right-Arm Medium|Left-Arm Medium|Right-Arm Spin|Left-Arm Spin|None)$", message = "Invalid bowling style")
    @Schema(description = "Bowling style of the player (optional for pure batsmen, use 'None' if player doesn't bowl)", example = "Right-Arm Fast", nullable = true, allowableValues = {
            "Right-Arm Fast", "Left-Arm Fast", "Right-Arm Medium", "Left-Arm Medium", "Right-Arm Spin", "Left-Arm Spin",
            "None" })
    private String bowlingStyle;

    // storing stats as embedded document, hence made another model for it
    @Valid // to validate stats also
    @Schema(description = "Player's career statistics (embedded document)")
    private Stats stats;
}
