package com.example.tournament_data.model;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Document(collection = "teams")
@Schema(description = "Team entity representing a cricket team in the tournament")
public class Team {
    @Id
    @Schema(description = "Unique identifier of the team (auto-generated by MongoDB)", example = "64a1b2c3d4e5f6g7h8i9j0k1", accessMode = Schema.AccessMode.READ_ONLY)
    private String id;

    @NotBlank(message = "Team Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Schema(description = "Official name of the team", example = "Mumbai Indians", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String teamName;

    @NotBlank(message = "Home Ground is required")
    @Size(min = 2, max = 100, message = "Ground name must be between 2 and 100 characters")
    @Schema(description = "Home stadium/ground where the team plays their home matches", example = "Wankhede Stadium, Mumbai", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String homeGround;

    // referencing to a player
    @Schema(description = "Player ID of the team captain (must be a player in the team, null if no captain assigned)", example = "64a1b2c3d4e5f6g7h8i9j0k2", nullable = true)
    private String captainId;

    @NotBlank(message = "Coach Name is required")
    @Size(min = 2, max = 100, message = "Coach name must be between 2 and 100 characters")
    @Schema(description = "Full name of the team's head coach", example = "Mahela Jayawardene", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String coach;

    @NotNull(message = "Player IDs list cannot be null")
    @Size(max = 25, message = "Team cannot have more than 25 players")
    @Schema(description = "List of player IDs belonging to this team (maximum 25 players allowed)", example = "[\"64a1b2c3d4e5f6g7h8i9j0k3\", \"64a1b2c3d4e5f6g7h8i9j0k4\"]", maxLength = 25)
    private List<String> playerIds = new ArrayList<>();

    public Team() {
    }

    public Team(String teamName, String homeGround, String captainId, String coach, List<String> playerIds) {
        this.teamName = teamName;
        this.homeGround = homeGround;
        this.coach = coach;
        this.captainId = captainId;
        this.playerIds = playerIds;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCaptainId() {
        return captainId;
    }

    public void setCaptainId(String captainId) {
        this.captainId = captainId;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getHomeGround() {
        return homeGround;
    }

    public void setHomeGround(String homeGround) {
        this.homeGround = homeGround;
    }

    public String getCoach() {
        return coach;
    }

    public void setCoach(String coach) {
        this.coach = coach;
    }

    public List<String> getPlayerIds() {
        return playerIds;
    }

    public void setPlayerIds(List<String> playerIds) {
        this.playerIds = playerIds;
    }

    @Override
    public String toString() {
        return "Team [id=" + id + ", teamName=" + teamName + ", homeGround=" + homeGround + ", captainId=" + captainId
                + ", coach=" + coach + ", playerIds=" + playerIds + "]";
    }

}
