package com.example.tournament_data.model;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "teams")
@Schema(description = "Team entity representing a cricket team in the tournament")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Team {
    @Transient
    public static final String SEQUENCE_NAME = "teams_sequence";
    
    @Id
    @Schema(description = "Unique identifier of the team (auto-generated by MongoDB)", example = "4", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer id;

    @NotBlank(message = "Team Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Schema(description = "Official name of the team", example = "Mumbai Indians", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String teamName;

    @NotBlank(message = "Home Ground is required")
    @Size(min = 2, max = 100, message = "Ground name must be between 2 and 100 characters")
    @Schema(description = "Home stadium/ground where the team plays their home matches", example = "Wankhede Stadium, Mumbai", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String homeGround;

    // referencing to a player
    @Schema(description = "Player ID of the team captain (must be a player in the team, null if no captain assigned)", example = "1", nullable = true)
    private Integer captainId;

    @NotBlank(message = "Coach Name is required")
    @Size(min = 2, max = 100, message = "Coach name must be between 2 and 100 characters")
    @Schema(description = "Full name of the team's head coach", example = "Mahela Jayawardene", requiredMode = Schema.RequiredMode.REQUIRED, minLength = 2, maxLength = 100)
    private String coach;

    @Size(max = 25, message = "Team cannot have more than 25 players")
    @Schema(description = "List of player IDs belonging to this team (maximum 25 players allowed)", example = "[\"1\", \"2\"]", maxLength = 25)
    private List<Integer> playerIds = new ArrayList<>();
}
